[profile.default]
src = "src"
out = "out"
# libs = ["lib"]
fs_permissions = [{access = "write", path = "./bytecode/"}]
ffi = true
solc_version = "0.8.19"
evm_version = "paris"

[fuzz]
runs = 1024

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = false
ignore = [
  "lib/**",
  "src/lib/**",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
