[package]
name = "rsa-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.73"
authors = ["Axis"]

[dependencies]
clap = { version = "^4.2.5", features = ["derive"] }
ethers = "^2.0"
rsa = { git = "https://github.com/Oighty/RSA", features = ["sha2"] }