name: test

on:
    push:
        branches:
            - master
    pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v2

      - uses: pnpm/action-setup@v2
        with:
            version: 8

      - name: Install Node dependencies
        run: pnpm install

      # From: https://ectobit.com/blog/speed-up-github-actions-rust-pipelines/
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build local rsa-cli for use int testing
        run: cd crates/rsa-cli && cargo build && cd ../..

      - name: Build local ecies-cli for use int testing
        run: cd crates/ecies-cli && cargo build && cd ../..

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Foundry dependencies
        run: forge install

      - name: Run lint check
        run: pnpm run lint:check

      - name: Run Forge build
        run: |
          forge --version
          forge build
        id: build

      - name: Run Forge tests
        run: |
          pnpm run test
        id: test

      - name: Contract Sizes
        run: |
          forge --version
          pnpm run size
        id: sizes
