name: test

on:
    push:
        branches:
            - master
    pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v2

      - uses: pnpm/action-setup@v2
        with:
            version: 8

      - name: Install Node dependencies
        run: pnpm install

      - name: Build local rsa-cli for use int testing
        run: cd rsa-cli && cargo build && cd ..

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          # 2024-02-10
          version: nightly-e897bd6874312d2c2d9acc7d24081ef721845b29

      - name: Install Foundry dependencies
        run: forge install

      - name: Run lint check
        run: pnpm run lint:check

      - name: Run Forge build
        run: |
          forge --version
          forge build
        id: build

      - name: Run Forge tests
        run: |
          pnpm run test
        id: test

      - name: Contract Sizes
        run: |
          forge --version
          pnpm run size
        id: sizes
